name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.2

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.1
  google_sign_in: ^6.1.6
  google_sign_in_web: ^0.12.4+4
  firebase_auth_web: ^5.9.2

flutter:
  assets:
    - assets/images/Background.png
    - assets/images/Google.png
    - assets/images/India.jpg
    - assets/images/Logo.png
    - assets/images/RA.png
    - assets/images/homescreen.png
